### ISSUE TITLE
env.js does not accept paths within a server address

### ISSUE THREAD

**Issue by Elscha** [Student-Management-System/StudentMgmt-Client#12]
### Problem
When using Sparky service as gateway to the Backend, I cannot use the URL given by Sparky service at the client.

### Steps to Reproduce
1) Make Backend available through Sparky service, e.g.,: `http://147.172.178.30:8080/stmgmt`
1) Configure `env.js` to query the Backend via Sparky service: `window.__env.API_BASE_PATH = "http://147.172.178.30:8080/stmgmt/";`
1) Start client and debug JavaScript traffic. Client tries to access Backend via the root path of Sparky service `http://147.172.178.30:8080` but not via `http://147.172.178.30:8080/stmgmt`

**Comment by klingebiel** [comment]
First of all, the URL should **NOT** have a trailing slash at the end.

Setting `window.__env.API_BASE_PATH = "http://147.172.178.30:8080/stmgmt";` produces the following URL:
`url: "http://147.172.178.30:8080/stmgmt/courses..."` when querying courses, so it does use the specified path.

If there's a problem with the routing, the problem must be somewhere else, not in the client.

**Comment by Elscha** [comment]
Sorry, you're right the route is corrctly composed. However, the client still produces a message that it cannot connect to the server
![Client](https://user-images.githubusercontent.com/6489033/93416252-ac2acd80-f8a5-11ea-8b13-9bd68d3de140.png)

**Comment by mspark** [comment]
@klingebiel 
Let's have a closer look on the responses. The response headers are modified via SparkyService; Is there anything which could produce problems on client side ? 

**Call and response via SparkyService**
`[marcel@radon net.ssehub.sparkyservice]% curl -X GET "http://147.172.178.30:8080/stmgmt/courses" -H "accept: application/json" -H "Authorization: Bearer undefined" -i `      
```                                                                                                                                                                                        
HTTP/1.1 200 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-total-count
x-total-count: 4
ETag: W/"2f4-ZcquU8Bp0chQ9b/4YP6Y6UxDIqw"
Date: Thu, 17 Sep 2020 08:29:56 GMT
Keep-Alive: timeout=5
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked

[{"id":"java-wise1920","shortname":"java","semester":"wise1920","title":"Programmierpraktikum I: Java","isClosed":false,"links":[{"name":"Example URL","url":"http://example-url.com"}]},{"id":"java-wise1819","shortname":"java","semester":"wise1819","title":"Programmierpraktikum I: Java","isClosed":true,"links":[{"name":"Example URL","url":"http://example-url.com"}]},{"id":"java-sose2020","shortname":"java","semester":"sose2020","title":"Programmierpraktikum I: Java","isClosed":false,"links":[{"name":"Example URL","url":"http://example-url.com"}]},{"id":"info2-sose2020","shortname":"info2","semester":"sose2020","title":"Informatik II: Algorithmen und Datenstrukturen","isClosed":false,"links":[{"name":"Example URL",
```

**Call and Response via StudentMgmt-Backend:** 

`[marcel@radon net.ssehub.sparkyservice]% curl -X GET "http://147.172.178.30:3000/courses" -H "accept: application/json" -H "Authorization: Bearer undefined" -i `
```                                                                                                                                                                                                     
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-total-count
x-total-count: 4
Content-Type: application/json; charset=utf-8
Content-Length: 756
ETag: W/"2f4-ZcquU8Bp0chQ9b/4YP6Y6UxDIqw"
Date: Thu, 17 Sep 2020 08:30:05 GMT
Connection: keep-alive
Keep-Alive: timeout=5

[{"id":"java-wise1920","shortname":"java","semester":"wise1920","title":"Programmierpraktikum I: Java","isClosed":false,"links":[{"name":"Example URL","url":"http://example-url.com"}]},{"id":"java-wise1819","shortname":"java","semester":"wise1819","title":"Programmierpraktikum I: Java","isClosed":true,"links":[{"name":"Example URL","url":"http://example-url.com"}]},{"id":"java-sose2020","shortname":"java","semester":"sose2020","title":"Programmierpraktikum I: Java","isClosed":false,"links":[{"name":"Example URL","url":"http://example-url.com"}]},{"id":"info2-sose2020","shortname":"info2","semester":"sose2020","title":"Informatik II: Algorithmen und Datenstrukturen","isClosed":false,"links":[{"name":"Example URL",
```

(*Note that eaxh request send an illegal Authorization Header: `Authorization Bearer undefined`)

**Comment by klingebiel** [comment]
The request is failing due to a CORS error related to the `Access-Control-Allow-Origin` header, which seems to be added twice:
```
Access to XMLHttpRequest at 'http://147.172.178.30:8080/stmgmt/courses?skip=0&take=15&semester=sose2020' from origin 'http://147.172.178.30' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
``` 

Have there been any changes regarding the header configuration ?

**Comment by mspark** [comment]
In Addition: We *think* the CORS error produce the behavior of the client. 

The current headers matches with the ones from my latest comment; so since then, no modifications were made there. 

All CORS relevant headers from the response:
```
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-total-count
```
All `Vary:` headers are probably added through the routing module of sparkyservice.  I'll remove them for further checks.

**Comment by mspark** [comment]
@klingebiel Is any of StudentMgmt-Applications adding any CORS headers ?

**Comment by mspark** [comment]
I can verify that the CORS configuration is correctly done by Sparkyservice. Removing any of them, will deny any proxy request due to missing CORS headers. 
In the browsers network tab we see the duplicate header when monitoring the StudenMgmt-Client:

![Screenshot_20201001_130542](https://user-images.githubusercontent.com/14931470/94801874-f99b5480-03e6-11eb-9fbf-c1ed3b274e59.png)

First thoughts were, that curl may filter the duplicate headers but a direct call to the backend address (via Sparkyservice) with Firefox only shows a single Access header as well.  
After removing all CORS configuration from Sparkyservice, the headers only appear when calling StudenMgmt-Backend. As expected the StudenMgmt-Backend adds own CORS configuration headers. Actually this shouldn't be a problem andshouldn't be result in duplicate Access-Controll-Headers! And as written before; this does not happen when calling the backend address without the client (http://147.172.178.30:8080/stmgmt/courses?skip=0&take=15&semester=sose2020). This problem only occur when the StudenMgmt-Client makes the request. I still don't know why this happens. 

A simple fix would be to disable CORS configuration in the StudenMgmt-Backend but this can lead to new errors when something else uses the service. Zuul (the used framework for routing in sparkyservice) can handle something like this. A patch is currently in testing.
